services:
  backend:
    image: dev-ops-backend:jenkins
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    container_name: backend
    # networks:
    #   - dev-ops-net
    restart: unless-stopped
    ports:
      - "5000:5000"

  frontend:
    image: dev-ops-frontend:jenkins
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    container_name: frontend
    # networks:
    #   - dev-ops-net
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend